function J = jacobianScara(l_2,l_3,theta_1,theta_2,theta_3)
%JACOBIANSCARA
%    J = JACOBIANSCARA(L_2,L_3,THETA_1,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Dec-2021 12:22:04

t2 = cos(theta_1);
t3 = cos(theta_2);
t4 = sin(theta_1);
t5 = sin(theta_2);
t6 = theta_2+theta_3;
t7 = l_2.*t3;
t8 = cos(t6);
t9 = l_2.*t5;
t10 = sin(t6);
t11 = l_3.*t8;
t12 = l_3.*t10;
t13 = t4.*t10;
t14 = -t10;
t15 = t2.*t8;
t16 = t4.*t8;
t17 = t2.*t10;
t18 = -t13;
t19 = -t15;
t20 = -t16;
t21 = t2.*t14;
t22 = t7+t11;
t23 = t9+t12;
J = reshape([t20,t15,0.0,t13,t21,0.0,t2,t4,0.0,-t4.*t22,t2.*t22,0.0,t21,t18,t8,t19,t20,t14,0.0,0.0,0.0,-t2.*t23,-t4.*t23,t22,t21,t18,t8,t19,t20,t14,0.0,0.0,0.0,-t2.*t12,-t4.*t12,t11],[12,3]);
